name: media
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.15.0
  just_audio: ^0.10.5
  video_player: ^2.10.1
  hive_flutter: ^1.1.0
  location: ^6.0.2
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
